apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: BackstageApp
  description: An example of a Backstage application.
  annotations: 
    circleci.com/project-slug: github/ashhar-globalwavenet/BackstageApp
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
